# Generated by Django 4.2.4 on 2023-08-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_rename_uname_tweet_user_tweet_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
    ]
